---

# https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-join/
- name: 'Join worker node'
  ansible.builtin.shell: |
    kubeadm join control.k8s.local:6443 \
      --node-name {{ inventory_hostname }} \
      --token {{ k8s.token }} \
      --discovery-token-unsafe-skip-ca-verification
    sleep 10

- ansible.builtin.import_tasks: '10_kube-config.yaml'
- ansible.builtin.import_tasks: '80_ufw.yaml'
