---

- name: 'Apt install haproxy'
  ansible.builtin.apt:
    state: 'present'
    pkg:
      - 'haproxy'

- name: 'Copy haproxy config'
  ansible.builtin.template:
    src: 'haproxy.cfg'
    dest: '/etc/haproxy/haproxy.cfg'
    mode: '0644'
    force: true
  notify: reload_haproxy
