---

- name: 'Apt install ufw'
  ansible.builtin.apt:
    state: 'present'
    pkg:
      - 'ufw'

- name: 'Enable ufw logging'
  community.general.ufw:
    logging: 'on'
  notify: reload_ufw

- name: 'Ufw default deny incoming'
  community.general.ufw:
    default: 'deny'
    direction: 'incoming'
  notify: reload_ufw

- name: 'Ufw default allow outgoing'
  community.general.ufw:
    default: 'allow'
    direction: 'outgoing'
  notify: reload_ufw

- name: 'Ufw allow ssh'
  community.general.ufw:
    rule: 'allow'
    port: 22
    proto: 'tcp'
  notify: reload_ufw

- name: 'Ufw allow HTTP'
  community.general.ufw:
    rule: 'allow'
    port: 80
    proto: 'tcp'
  notify: reload_ufw

- name: 'Ufw allow HTTPS'
  community.general.ufw:
    rule: 'allow'
    port: 443
    proto: 'tcp'
  notify: reload_ufw

- name: 'Ufw allow K8s API'
  community.general.ufw:
    rule: 'allow'
    port: 6443
    proto: 'tcp'
  notify: reload_ufw
