---

# https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-init/
- name: 'Initialize control-plane node'
  ansible.builtin.shell: |
    kubeadm init \
      --node-name {{ inventory_hostname }} \
      --apiserver-advertise-address {{ ansible_host }} \
      --apiserver-bind-port 6443 \
      --pod-network-cidr 10.244.0.0/16 \
      --token {{ k8s.token }} \
      --token-ttl 10m
    sleep 10

- ansible.builtin.import_tasks: '10_kube-config.yaml'
- ansible.builtin.import_tasks: '20_flannel.yaml'
- ansible.builtin.import_tasks: '80_ufw.yaml'
