---

- name: 'Set hostname'
  ansible.builtin.hostname:
    name: '{{ inventory_hostname }}'

- name: 'Update apt cache'
  ansible.builtin.apt:
    update_cache: true

- name: 'Apt dist upgrade'
  ansible.builtin.apt:
    upgrade: 'dist'

- name: 'Enable unattended upgrades'
  ansible.builtin.apt:
    pkg:
      - 'apt-listchanges'
      - 'unattended-upgrades'
    state: 'present'

- name: 'Install locales'
  ansible.builtin.apt:
    state: 'present'
    pkg:
      - 'locales'

- name: 'Set locales'
  community.general.locale_gen:
    name: 'en_US.UTF-8'
    state: 'present'

- name: 'Set timezone'
  community.general.timezone:
    name: 'Europe/Berlin'

- ansible.builtin.import_tasks: 'ufw.yaml'
