---

- name: 'Include k8s secrets'
  ansible.builtin.include_vars:
    file: 'secrets/k8s.yaml'
    name: 'k8s'

- name: 'Install apt https transport'
  ansible.builtin.apt:
    pkg:
      - 'apt-transport-https'
      - 'ca-certificates'
      - 'curl'
      - 'gpg'
    state: 'present'

- name: 'Install containerd'
  ansible.builtin.apt:
    pkg:
      - 'containerd'
      - 'containernetworking-plugins'
    state: 'present'

- name: 'Hold containerd apt package'
  ansible.builtin.dpkg_selections:
    name: 'containerd'
    selection: hold

- name: 'Hold containernetworking-plugins apt package'
  ansible.builtin.dpkg_selections:
    name: 'containernetworking-plugins'
    selection: hold

- name: 'Copy K8s apt gpg key'
  ansible.builtin.copy:
    src: 'k8s-apt.gpg'
    dest: '/etc/apt/keyrings/k8s.gpg'
    mode: '0644'
    force: true

- name: 'Add apt repository'
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/k8s.gpg] https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /"
    filename: k8s
    state: present

- name: 'Update apt cache'
  ansible.builtin.apt:
    update_cache: true

- name: 'Install K8s apt packages'
  ansible.builtin.apt:
    pkg:
      - 'kubelet'
      - 'kubeadm'
      - 'kubectl'
    state: 'present'

- name: 'Hold kubelet apt package'
  ansible.builtin.dpkg_selections:
    name: 'kubelet'
    selection: hold

- name: 'Hold kubeadm apt package'
  ansible.builtin.dpkg_selections:
    name: 'kubeadm'
    selection: hold

- name: 'Hold kubectl apt package'
  ansible.builtin.dpkg_selections:
    name: 'kubectl'
    selection: hold

- name: 'Configure network'
  ansible.builtin.shell: |
    modprobe br_netfilter
    sysctl net.bridge.bridge-nf-call-iptables=1
    sysctl net.ipv4.ip_forward=1

- name: 'Disable swap'
  ansible.builtin.shell: |
    swapoff -a
    sed -i '/ swap / s/^/#/' /etc/fstab
